
default_platform(:ios)

platform :ios do
  desc "Create App"
  lane :create_app do
    produce
  end

desc "Create ipa"
  lane :build do
    update_code_signing_settings
    increment_build_number
    gym
  end

end
